<?php
/**
 * TrackingResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TrackingResponseTest Class Doc Comment
 *
 * @category    Class
 * @description TrackingResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TrackingResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TrackingResponse"
     */
    public function testTrackingResponse()
    {
    }

    /**
     * Test attribute "opens"
     */
    public function testPropertyOpens()
    {
    }

    /**
     * Test attribute "clicks_html"
     */
    public function testPropertyClicksHtml()
    {
    }

    /**
     * Test attribute "clicks_text"
     */
    public function testPropertyClicksText()
    {
    }

    /**
     * Test attribute "additional_params"
     */
    public function testPropertyAdditionalParams()
    {
    }
}
